### PR TITLE
Added Docker

### PR DESCRIPTION
**Pull request by obduk**

### CODE REVIEW

**Comment by errordeveloper** [comment]
First thing, you probably want to read about the [whole layering shenanigans](http://blog.tutum.co/2014/10/22/how-to-optimize-your-dockerfile/), and move all `RUN` statements into a shell script (unless you really don't care about how long it takes to pull the image on a freshly provisioned machine).

**Comment by errordeveloper** [comment]
A optimisation for later would be to avoid build dependencies in the production runtime image (i.e. Puppet and things like GCC etc). You don't have to, I am just saying, as it's one of the things you can afford with containers and you might wish to bare in mind. There a few approaches to it, currently may be not quite straight forward, but hopefully Docker folks will work it out (there are a few current efforts: docker/docker#12072 and [jamiemccrindle/dockerception](https://github.com/jamiemccrindle/dockerception)).

**Comment by errordeveloper** [comment]
Aside from that, am I right in understanding that this is just on Rails app inside the container and no other daemons? As you might have learned, you can throw the database and all sorts of things into your container, which some people do, but majority of people are not quite convinced.

**Comment by errordeveloper** [comment]
And, I don't know if you have seen, but there exists the kind of official [Rails image](https://registry.hub.docker.com/_/rails/), which I haven't used and don't know much about. It's a thing.

**Comment by obduk** [comment]
Thanks for looking at this, have made some changes

1. I have combined a number of the run commands to reduce the number of layers
2. I have also tried to uninstall some of the build dependencies
3. It is just a rails app, I use Amazon Elastic Beanstalk with RDS for the database, seems to work quite nicely
4. I have seen the rails and ruby images, at the moment I want to keep my dev (which uses vagrant) and prod ruby installs the same at the moment, but will probably look at a better way in future as will not need RVM or multiple rubies with this which will be nice.

**Pull request merged**
